services:
  web:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "3000:3000"
    working_dir: /as-css
    stdin_open: true
    tty: true
    command: ["bin/rails", "server", "-b", "0.0.0.0"]
